/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}/products.index'
import { Route as Char123LocaleChar125ProductsSearchRouteImport } from './routes/{-$locale}/products.search'
import { Route as Char123LocaleChar125ProductsSlugRouteImport } from './routes/{-$locale}/products.$slug'
import { Route as Char123LocaleChar125ProductsSlugPaymentRouteImport } from './routes/{-$locale}/products.$slug.payment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsSearchRoute =
  Char123LocaleChar125ProductsSearchRouteImport.update({
    id: '/products/search',
    path: '/products/search',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsSlugRoute =
  Char123LocaleChar125ProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsSlugPaymentRoute =
  Char123LocaleChar125ProductsSlugPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => Char123LocaleChar125ProductsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$slug': typeof Char123LocaleChar125ProductsSlugRouteWithChildren
  '/{-$locale}/products/search': typeof Char123LocaleChar125ProductsSearchRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/products/$slug/payment': typeof Char123LocaleChar125ProductsSlugPaymentRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$slug': typeof Char123LocaleChar125ProductsSlugRouteWithChildren
  '/{-$locale}/products/search': typeof Char123LocaleChar125ProductsSearchRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/products/$slug/payment': typeof Char123LocaleChar125ProductsSlugPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/products/$slug': typeof Char123LocaleChar125ProductsSlugRouteWithChildren
  '/{-$locale}/products/search': typeof Char123LocaleChar125ProductsSearchRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/products/$slug/payment': typeof Char123LocaleChar125ProductsSlugPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/'
    | '/{-$locale}/products/$slug'
    | '/{-$locale}/products/search'
    | '/{-$locale}/products/'
    | '/{-$locale}/products/$slug/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}'
    | '/{-$locale}/products/$slug'
    | '/{-$locale}/products/search'
    | '/{-$locale}/products'
    | '/{-$locale}/products/$slug/payment'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/'
    | '/{-$locale}/products/$slug'
    | '/{-$locale}/products/search'
    | '/{-$locale}/products/'
    | '/{-$locale}/products/$slug/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/search': {
      id: '/{-$locale}/products/search'
      path: '/products/search'
      fullPath: '/{-$locale}/products/search'
      preLoaderRoute: typeof Char123LocaleChar125ProductsSearchRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/$slug': {
      id: '/{-$locale}/products/$slug'
      path: '/products/$slug'
      fullPath: '/{-$locale}/products/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ProductsSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/$slug/payment': {
      id: '/{-$locale}/products/$slug/payment'
      path: '/payment'
      fullPath: '/{-$locale}/products/$slug/payment'
      preLoaderRoute: typeof Char123LocaleChar125ProductsSlugPaymentRouteImport
      parentRoute: typeof Char123LocaleChar125ProductsSlugRoute
    }
  }
}

interface Char123LocaleChar125ProductsSlugRouteChildren {
  Char123LocaleChar125ProductsSlugPaymentRoute: typeof Char123LocaleChar125ProductsSlugPaymentRoute
}

const Char123LocaleChar125ProductsSlugRouteChildren: Char123LocaleChar125ProductsSlugRouteChildren =
  {
    Char123LocaleChar125ProductsSlugPaymentRoute:
      Char123LocaleChar125ProductsSlugPaymentRoute,
  }

const Char123LocaleChar125ProductsSlugRouteWithChildren =
  Char123LocaleChar125ProductsSlugRoute._addFileChildren(
    Char123LocaleChar125ProductsSlugRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125ProductsSlugRoute: typeof Char123LocaleChar125ProductsSlugRouteWithChildren
  Char123LocaleChar125ProductsSearchRoute: typeof Char123LocaleChar125ProductsSearchRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125ProductsSlugRoute:
      Char123LocaleChar125ProductsSlugRouteWithChildren,
    Char123LocaleChar125ProductsSearchRoute:
      Char123LocaleChar125ProductsSearchRoute,
    Char123LocaleChar125ProductsIndexRoute:
      Char123LocaleChar125ProductsIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
